name: tv_series
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  external_video_player_launcher: ^0.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_login_template: ^1.1.0
  go_router: ^13.2.1
  http: ^1.1.0
  intl: any
  logger: ^2.3.0
  shared_preferences: ^2.2.3
  url_strategy: ^0.2.0
  video_player: ^2.8.3
  flutter_ffmpeg: ^0.4.0
  path_provider: ^2.0.11
  chewie: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/LogoProje.png"

flutter:
  uses-material-design: true
  generate: true  
  assets:
    - assets/videos/
    - assets/images/
    - assets/images/moviePosters/
    - assets/data/
